sudo: required
language: ruby
services:
- docker
cache:
  directories:
    - $HOME/docker
before_install:
# Load cached docker images
- if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
script:
- cd stage-0 && ./build.sh && cd ..
- cd stage-1 && ./build.sh && cd ..
- cd stage-2 && ./build.sh && cd ..
after_script:
- zip -r docker-kali.zip out
before_cache:
# Save tagged docker images
- >
  mkdir -p $HOME/docker && docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}} {{.ID}}'
  | xargs -n 2 -t sh -c 'test -e $HOME/docker/$1.tar.gz || docker save $0 | gzip -2 > $HOME/docker/$1.tar.gz'
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: AlFstR5NrlXFU9+TEYXGTFivYQGv7GgTehcTAODVhfn6J9rmjYMqN0M7xWtszPV3APRrDnkrlbd49qM0EpDAw88Xm5QJv++aSJ9wWPPr1R5fmvMU9p3FARsptz1vFoKntGwOBp34hpuiOxMg4ylrB0DZ001rnXp5AgZwtGbz8noX1Vw0HjpblDcqX+Tph1W5YO1c3xe9MzDZ6msTGAnS6Stt3RdeSK3kpElekX9wo4svG5VPD2dx8Yx1DCK41grJOa7eL+gQ1UU09+B9phoMLKMbUVaDg07pb7AlKbqWklIuHSDhJgvIoEgaYu8mAUvD9uYPGaCvg1wgIh8dr9lD0RWDRZYTCxdT6srxzpRE3vn45WFSaC0KRXavkHXgoe4SRGhepWR01vBPhYBzbmG0QDY/AKuyKR/m0uc4H2x+joG0jg9Sax2zPN7vSSKEC2doOFi/0oKRYjeDVJCarwHSKXJOR/YVH61lsuQx030EohyBgjlwhlaWQhGk1TqoqMcUfr+y7i71RksBlSeCcmlHBzG4WF39/R0wgKMVZHJrlLyrGzLRAUViwb8JKxakmDXMEuxhU4i5P5/c+5erbeiABAZZ5YZp0v6yECPV86coU3MINO/nowS2gSzGvLpr+WXd+kng0nPLHzZq8Jjl96QOiuVda0KL3yaq80z0gz1ou8k=
  file: docker-kali.zip
  on:
    repo: vincentriemer/docker-kali
